class GroqRecipeFormatter {
  String format(Map<String, dynamic> result) {
    final recipes = result['recipes'];

    if (recipes is! List || recipes.isEmpty) {
      return result['message']?.toString() ??
          'No AI suggestion available from Groq.';
    }

    final buffer = StringBuffer();

    buffer.writeln('Generated by Groq AI');
    buffer.writeln('');

    for (var i = 0; i < recipes.length; i++) {
      final recipe = recipes[i] as Map<String, dynamic>;

      final title = recipe['title']?.toString() ?? 'Recipe ${i + 1}';
      final ingredientsUsed = _stringList(recipe['ingredientsUsed']);
      final missingIngredients = _stringList(recipe['missingIngredients']);
      final steps = _stringList(recipe['steps']);
      final whyRecommended =
          recipe['whyRecommended']?.toString() ??
          'Recommended to reduce waste.';

      buffer.writeln('${i + 1}. $title');
      buffer.writeln('');
      buffer.writeln('Ingredients Used:');

      for (final item in ingredientsUsed) {
        buffer.writeln('- $item');
      }

      if (missingIngredients.isNotEmpty) {
        buffer.writeln('');
        buffer.writeln('Missing Ingredients:');

        for (final item in missingIngredients) {
          buffer.writeln('- $item');
        }
      }

      buffer.writeln('');
      buffer.writeln('Steps:');

      for (var stepIndex = 0; stepIndex < steps.length; stepIndex++) {
        buffer.writeln('${stepIndex + 1}. ${steps[stepIndex]}');
      }

      buffer.writeln('');
      buffer.writeln('Why Recommended:');
      buffer.writeln(whyRecommended);

      if (i != recipes.length - 1) {
        buffer.writeln('');
        buffer.writeln('---');
        buffer.writeln('');
      }
    }

    return buffer.toString().trim();
  }

  List<String> _stringList(dynamic value) {
    if (value is List) {
      return value.map((item) => item.toString()).toList();
    }

    return [];
  }
}
