// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRVAshbBtrK_wErRc5-A8UcksJNBam4s',
    appId: '1:384873169563:web:80da212022315171b63c3e',
    messagingSenderId: '384873169563',
    projectId: 'velora-73222',
    authDomain: 'velora-73222.firebaseapp.com',
    storageBucket: 'velora-73222.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWeMhCyi9wNOivv8ubdOWQ-DX0D6oDibM',
    appId: '1:384873169563:android:d83c95f3e2134983b63c3e',
    messagingSenderId: '384873169563',
    projectId: 'velora-73222',
    storageBucket: 'velora-73222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnfpIQabkCvrdR4ogebc2jLlvBC0eDTbY',
    appId: '1:384873169563:ios:bb11a6515ca104d3b63c3e',
    messagingSenderId: '384873169563',
    projectId: 'velora-73222',
    storageBucket: 'velora-73222.firebasestorage.app',
    iosBundleId: 'com.example.velora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnfpIQabkCvrdR4ogebc2jLlvBC0eDTbY',
    appId: '1:384873169563:ios:bb11a6515ca104d3b63c3e',
    messagingSenderId: '384873169563',
    projectId: 'velora-73222',
    storageBucket: 'velora-73222.firebasestorage.app',
    iosBundleId: 'com.example.velora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRVAshbBtrK_wErRc5-A8UcksJNBam4s',
    appId: '1:384873169563:web:db3de6c066168655b63c3e',
    messagingSenderId: '384873169563',
    projectId: 'velora-73222',
    authDomain: 'velora-73222.firebaseapp.com',
    storageBucket: 'velora-73222.firebasestorage.app',
  );
}
